# Generated by Django 4.1.7 on 2023-05-06 04:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0003_tag_task"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="deadline",
            field=models.DateTimeField(),
        ),
    ]
