# Generated by Django 4.1.7 on 2023-06-10 05:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0008_user_date_of_birth_user_phone"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="deadline",
            field=models.DateTimeField(null=True),
        ),
    ]
