# Generated by Django 4.1.7 on 2023-07-06 03:45

from django.db import migrations, models
import task_manager.services.storage_backends


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0009_alter_task_deadline"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="avatar_picture",
            field=models.ImageField(
                null=True,
                storage=task_manager.services.storage_backends.public_storage,
                upload_to="",
            ),
        ),
    ]
